os: Visual Studio 2015

version: 1.0.{build}

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VS_VERSION: 12 2013
      VS_PLATFORM: Win32
    - VS_VERSION: 12 2013
      VS_PLATFORM: x64
    - VS_VERSION: 14 2015
      VS_PLATFORM: Win32
    - VS_VERSION: 14 2015
      VS_PLATFORM: x64

before_build:
  - mkdir build && cd build
  - git submodule init
  - git submodule update
  - cmake -G "Visual Studio %VS_VERSION%"
    -DTASTYLIB_BUILD_TEST=ON
    -DCMAKE_BUILD_TYPE=%CONFIGURATION%
    -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%
    -DCMAKE_VERBOSE_MAKEFILE=ON
    ..

build:
  project: build\TastyLib.sln
  parallel: true
  verbosity: minimal

test_script:
  - ctest --verbose
